# Site wide configuration

title:            Scriptlore
locale:           en_US
url: 'http://scriptlore.com'
image_url: "http://scriptlore.com/images"

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Patrick Ogenstad
  avatar: ogenstad.jpg
  bio: "This site is in hybernation mode. To view my current work please visit <a href='http://networklore.com'>Networklore</a>."
  email:
  disqus-shortname:
  twitter: networklore
  facebook: #username
  google:
    plus: #username
    analytics: UA-359232-5
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: ogenstad
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: patrickogenstad
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
